import pandas as pd
import yaml
import helperFun

configfile: "config2.yaml"
res_config = yaml.load(open("resources.yaml"))

samples = pd.read_table(config["samples"], sep=",").replace(' ', '_', regex=True)

org_ref = set(zip(samples.Organism.tolist(), samples.refGenome.tolist(), samples.BioSample.tolist()))  # To get only unique combinations of organism and ref accession.
ORGANISM, REFGENOME, SAMPLES = map(list, zip(*org_ref))  # Split above back to indiviudal lists for expand. There probably is a better way?

rule all:
    input:
        expand(config['output'] + "{Organism}/{refGenome}/" + config['bamDir'] + "{sample}" + config['bam_suffix'], zip, Organism=ORGANISM, refGenome=REFGENOME, sample=SAMPLES)
include: "rules/common.smk"	
include: "rules/fastq2bam.smk"

