#!/bin/sh
# Copyright (c) 2014-2020 Sentieon Inc. All rights reserved
install_dir="$SENTIEON_INSTALL_DIR"

for prog in ${SENTIEON_PYTHON:-python3 python2 python}
do
    vers=$("$prog" --version 2>&1)
    vers=$(expr "$vers" : 'Python \([0-9]*.[0-9]*\)')
    [ "$vers" ] || continue
    if [ -d "$install_dir/lib/python$vers" ]; then
	PYTHONPATH="$install_dir/lib/python$vers:${PYTHONPATH##:}"
    fi
    PYTHONPATH="$install_dir/lib/python/sentieon:${PYTHONPATH##:}"
    PYTHONPATH="${PYTHONPATH%%:}" # remove trailing :
    export PYTHONPATH
    break
done

exec "$prog" -m $(basename "$0") "$@"
