###
# fastq2bam workflow
##

# fastq download
get_fastq_pe:
    threads: 8
    mem: 2000
# compress fastq
gzip_fastq:
    mem: 4000
# fastp program
fastp: 
    threads: 15
    mem: 2500
# index reference
index_ref:
    mem: 10000
# bwa mapping
bwa_map: 
    threads: 31 
    mem: 2500
# sort bam with picard's SortSam tool
sort_bam: 
    mem: 2500 
# mark duplicates with picard's MarkDuplicates
dedup:
    threads: 31
    mem: 5000 
# calculate BAM summaries with samtools and picard
bam_sumstats: 
    mem: 2500 
merge_bams:
    mem: 2500

###
# Intervals workflow
###

# preprocess genome, create intervals
# picard's create CreateSequenceDictionary, samtools faidx
process_ref:
    mem: 1000
# custom python algo to create intervals
create_intervals:
    mem: 1000

###
# bam2vcf workflows
###

# gatk HaplotypeCaller
bam2gvcf: 
    mem: 2048
# gatk GenomicsDBImport
gvcf2DB:
    mem: 4068
# gatk GenotypeGVCFs 
DB2vcf: 
    mem: 4068
## freebayes program only! ##
bam2vcf:
    mem: 20000
# gatk filterVcfs
filterVcfs:
    mem: 4068
# gatk GatherVcfs
gatherVcfs:
    mem: 4068
# picard SortVcf
sortVcf:
    mem: 20000
# vcftools program
vcftools:
    mem: 20000
# bedtools program
bedtools:
    mem: 20000
# plink
plink:
    threads: 5